### PR TITLE
Migrate line.html

### PR DESCRIPTION
**Pull request by jimerino**
Hi!

I've done a prework to migrate line.html to d3 v5.5 (think would work in v4.x)

Hope this would be a initial milestone to start the work (and to discuss how to face the migration).

Regards!

### CODE REVIEW

**Comment by liquidpele** [comment]
This has stuff that shouldn't be n the PR...  the build file changes, plus package-lock.json for example.

**Comment by paullryan** [comment]
@liquidpele given the structure of the .gitignore these files would e expected to be updated. As for the package-lock.json you could just ignore it, however a lock like that (or a yarn.lock) makes is so all devs are working with the same dependency versions. Makes troubleshooting as a team much smoother. 

What would be your expected version of this?

**Comment by liquidpele** [comment]
Eh, I'm not that worried about it for a dev-heavy rewrite like this, so it's fine.

**Comment by paullryan** [comment]
In that case... want to merge this one so we can work from it? Or not happy with it?

**Comment by liquidpele** [comment]
Go for it!

**Comment by paullryan** [comment]
@liquidpele, given the last communication looks like you were ready to merge, please do when you get a chance so we can use it as a spring board for the other charts.

**Comment by liquidpele** [comment]
Merged.   By the way, I'm looking for people to help out maintain this project since I don't have much time for it anymore... if anyone is interested please hit me up.

**Pull request merged**
